pgpu-laion-5m-8192-test-ip:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  metric: dot
  lists: [90, 8192]
  samplingFactor: 256
  batchSize: 1000000
  residual_quantization: false
  workers: 63
  top: 10
  benchmarks:
    420-1.0:
      nprob: 4,20
      epsilon: 1.0
    430-1.0:
      nprob: 4,30
      epsilon: 1.0
    440-1.0:
      nprob: 4,40
      epsilon: 1.0
    450-1.0:
      nprob: 4,50
      epsilon: 1.0
    4100-1.0:
      nprob: 4,100
      epsilon: 1.0
    4020-1.0:
      nprob: 40,20
      epsilon: 1.0
    4030-1.0:
      nprob: 40,30
      epsilon: 1.0
    4040-1.0:
      nprob: 40,40
      epsilon: 1.0
    4050-1.0:
      nprob: 40,50
      epsilon: 1.0

    420-1.5:
      nprob: 4,20
      epsilon: 1.5
    430-1.5:
      nprob: 4,30
      epsilon: 1.5
    440-1.5:
      nprob: 4,40
      epsilon: 1.5
    450-1.5:
      nprob: 4,50
      epsilon: 1.5
    4020-1.5:
      nprob: 40,20
      epsilon: 1.5
    4030-1.5:
      nprob: 40,30
      epsilon: 1.5
    4040-1.5:
      nprob: 40,40
      epsilon: 1.5
    4050-1.5:
      nprob: 40,50
      epsilon: 1.5

    420-1.7:
      nprob: 4,20
      epsilon: 1.7
    430-1.7:
      nprob: 4,30
      epsilon: 1.7
    440-1.7:
      nprob: 4,40
      epsilon: 1.7
    450-1.7:
      nprob: 4,50
      epsilon: 1.7
    4020-1.7:
      nprob: 40,20
      epsilon: 1.7
    4030-1.7:
      nprob: 40,30
      epsilon: 1.7
    4040-1.7:
      nprob: 40,40
      epsilon: 1.7
    4050-1.7:
      nprob: 40,50
      epsilon: 1.7


