pgpu-laion-5m-190-35000-test-ip:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  metric: dot
  samplingFactor: 256
  lists: [190, 35000]
  batchSize: 1000000
  residual_quantization: true
  pg_parallel_workers: 32
  top: 10
  benchmarks:
    50-100-1.5:
      nprob: 50,100
      epsilon: 1.5
    50-100-1.9:
      nprob: 50,100
      epsilon: 1.9