pgvector-deep1B-m16-128:
  dataset: deep1b-test-l2
  datasetType: npy
  pg_parallel_workers: 32
  metric: l2
  m: 16
  efConstruction: 128
  top: 10
  benchmarks:
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }
    "1000": { efSearch: 1000 }
    "1200": { efSearch: 1200 }
