pgvector-laion-5m-m12-64:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 12
  efConstruction: 64
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m12-128:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 12
  efConstruction: 128
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m12-256:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 12
  efConstruction: 256
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m12-512:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 12
  efConstruction: 512
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m16-64:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 16
  efConstruction: 64
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m16-128:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 16
  efConstruction: 128
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m16-256:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 16
  efConstruction: 256
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m16-512:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 16
  efConstruction: 512
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m24-64:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 24
  efConstruction: 64
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m24-128:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 24
  efConstruction: 128
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m24-256:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 24
  efConstruction: 256
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m24-512:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 24
  efConstruction: 512
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m36-128:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 36
  efConstruction: 128
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m36-256:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 36
  efConstruction: 256
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }

pgvector-laion-5m-m36-512:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  pg_parallel_workers: 63
  metric: dot
  m: 36
  efConstruction: 512
  top: 10
  benchmarks:
    "10": { efSearch: 10 }
    "20": { efSearch: 20 }
    "40": { efSearch: 40 }
    "60": { efSearch: 60 }
    "80": { efSearch: 80 }
    "120": { efSearch: 120 }
    "200": { efSearch: 200 }
    "400": { efSearch: 400 }
    "600": { efSearch: 600 }
    "800": { efSearch: 800 }