vc-deep1B-800-640k:
  dataset: deep1b-test-l2
  datasetType: npy
  metric: l2
  samplingFactor: 256
  lists: [800, 640000]
  batchSize: 1000000
  kmeans_hierarchical: true
  residual_quantization: true
  build_threads: 32
  pg_parallel_workers: 32
  top: 10
  benchmarks:
    10-20-1.0:
      nprob: 10,20
      epsilon: 1.0
    10-20-1.5:
      nprob: 10,20
      epsilon: 1.5
    10-20-1.9:
      nprob: 10,20
      epsilon: 1.9
    15-30-1.0:
      nprob: 15,30
      epsilon: 1.0
    15-30-1.5:
      nprob: 15,30
      epsilon: 1.5
    15-30-1.9:
      nprob: 15,30
      epsilon: 1.9
    20-40-1.0:
      nprob: 20,40
      epsilon: 1.0
    20-40-1.5:
      nprob: 20,40
      epsilon: 1.5
    20-40-1.9:
      nprob: 20,40
      epsilon: 1.9
    25-50-1.0:
      nprob: 25,50
      epsilon: 1.0
    25-50-1.5:
      nprob: 25,50
      epsilon: 1.5
    25-50-1.9:
      nprob: 25,50
      epsilon: 1.9
    50-100-1.0:
      nprob: 50,100
      epsilon: 1.0
    50-100-1.5:
      nprob: 50,100
      epsilon: 1.5
    50-100-1.9:
      nprob: 50,100
      epsilon: 1.9
