vc-deep1B-800-640k:
  dataset: deep1b-test-l2
  datasetType: npy
  metric: l2
  samplingFactor: 256
  lists: [800, 640000]
  kmeans_hierarchical: true
  residual_quantization: true
  build_threads: 32
  pg_parallel_workers: 32
  top: 10
  benchmarks:
    30-200-1.5:
      nprob: 30,200
      epsilon: 1.5
    30-200-1.9:
      nprob: 30,200
      epsilon: 1.9
    40-200-1.5:
      nprob: 40,200
      epsilon: 1.5
    40-200-1.9:
      nprob: 40,200
      epsilon: 1.9
    40-250-1.5:
      nprob: 40,250
      epsilon: 1.5
    40-250-1.9:
      nprob: 40,250
      epsilon: 1.9
    50-250-1.5:
      nprob: 50,250
      epsilon: 1.5
    50-250-1.9:
      nprob: 50,250
      epsilon: 1.9
    60-350-1.5:
      nprob: 60,350
      epsilon: 1.5
    60-350-1.9:
      nprob: 60,350
      epsilon: 1.9

