vc-laion-5m-190-35k:
  dataset: laion-5m-test-ip
  datasetType: hdf5
  metric: dot
  samplingFactor: 256
  lists: [190, 35000]
  build_threads: 32
  residual_quantization: true
  kmeans_hierarchical: true
  pg_parallel_workers: 32
  top: 10
  benchmarks:
    15-30-1.9:
      nprob: 15,30
      epsilon: 1.9
    20-40-1.9:
      nprob: 20,40
      epsilon: 1.9
    38-76-1.9:
      nprob: 38,76
      epsilon: 1.9
    50-100-1.9:
      nprob: 50,100
      epsilon: 1.9
    65-130-1.9:
      nprob: 65,130
      epsilon: 1.9
    80-160-1.9:
      nprob: 80,160
      epsilon: 1.9